#!/bin/bash
set -e

# ============================================================================
# Local Development Configuration Setup Script
# ============================================================================
# This script extracts Terraform outputs and configures the local .NET app
# with the correct Azure AD and OBO settings.
#
# Usage:
#   ./scripts/setup-local-config.sh [--env-vars]
#
# Options:
#   --env-vars    Export as environment variables instead of updating appsettings
#
# Prerequisites:
#   - Terraform state must exist (run 'azd up' first)
#   - jq must be installed (brew install jq)
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INFRA_DIR="$PROJECT_ROOT/infra"
APP_DIR="$PROJECT_ROOT/src/MCPWrapper/MCPWrapper.Api"
APPSETTINGS_FILE="$APP_DIR/appsettings.Development.json"

# Detect azd environment name and state location
AZD_ENV_NAME=$(azd env get-values 2>/dev/null | grep AZURE_ENV_NAME | cut -d'=' -f2 | tr -d '"' || echo "")
if [ -n "$AZD_ENV_NAME" ]; then
  AZD_STATE_DIR="$PROJECT_ROOT/.azure/$AZD_ENV_NAME/infra"
else
  AZD_STATE_DIR=""
fi

USE_ENV_VARS=false
if [[ "$1" == "--env-vars" ]]; then
  USE_ENV_VARS=true
fi

# Color output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== MCP Proxy Local Configuration Setup ===${NC}\n"

# Check prerequisites
if ! command -v jq &> /dev/null; then
  echo -e "${RED}Error: jq is not installed. Install it with: brew install jq${NC}"
  exit 1
fi

if ! command -v terraform &> /dev/null; then
  echo -e "${RED}Error: terraform is not installed.${NC}"
  exit 1
fi

if [ ! -d "$INFRA_DIR" ]; then
  echo -e "${RED}Error: Infrastructure directory not found at $INFRA_DIR${NC}"
  exit 1
fi

# Determine where Terraform state is located
STATE_DIR=""
if [ -n "$AZD_STATE_DIR" ] && [ -f "$AZD_STATE_DIR/terraform.tfstate" ]; then
  echo "Found azd state in: .azure/$AZD_ENV_NAME/infra"
  STATE_DIR="$AZD_STATE_DIR"
elif [ -f "$INFRA_DIR/terraform.tfstate" ]; then
  echo "Found Terraform state in: infra/"
  STATE_DIR="$INFRA_DIR"
else
  echo -e "${RED}Error: Terraform state not found. Run 'azd up' first to provision infrastructure.${NC}"
  echo "  Checked: $INFRA_DIR/terraform.tfstate"
  if [ -n "$AZD_STATE_DIR" ]; then
    echo "  Checked: $AZD_STATE_DIR/terraform.tfstate"
  fi
  exit 1
fi

# Navigate to state directory
cd "$STATE_DIR"

echo "📦 Extracting Terraform outputs..."

# Extract Terraform outputs as JSON
TF_OUTPUT=$(terraform output -json 2>/dev/null)

if [ $? -ne 0 ] || [ -z "$TF_OUTPUT" ]; then
  echo -e "${RED}Error: Failed to extract Terraform outputs${NC}"
  exit 1
fi

# Parse individual values
TENANT_ID=$(echo "$TF_OUTPUT" | jq -r '.AZURE_TENANT_ID.value // empty')
CLIENT_ID=$(echo "$TF_OUTPUT" | jq -r '.MCP_PROXY_APP_CLIENT_ID.value // empty')
AUDIENCE=$(echo "$TF_OUTPUT" | jq -r '.MCP_PROXY_IDENTIFIER_URI.value // empty')
CLIENT_SECRET=$(echo "$TF_OUTPUT" | jq -r '.MCP_PROXY_CLIENT_SECRET.value // empty')
DOWNSTREAM_SCOPE=$(echo "$TF_OUTPUT" | jq -r '.OBO_SCOPE.value // empty')

# Validate required values
if [ -z "$TENANT_ID" ] || [ -z "$CLIENT_ID" ] || [ -z "$AUDIENCE" ]; then
  echo -e "${RED}Error: Missing required Terraform outputs${NC}"
  echo "  TENANT_ID: $TENANT_ID"
  echo "  CLIENT_ID: $CLIENT_ID"
  echo "  AUDIENCE: $AUDIENCE"
  exit 1
fi

# Warn if client secret is missing (might be using managed identity)
if [ -z "$CLIENT_SECRET" ]; then
  echo -e "${YELLOW}Warning: Client secret not found in outputs. This is expected if using managed identity only.${NC}"
  CLIENT_SECRET="<not-configured>"
fi

# Set default downstream scope if not configured
if [ -z "$DOWNSTREAM_SCOPE" ]; then
  echo -e "${YELLOW}Warning: Downstream API not configured. Using placeholder.${NC}"
  DOWNSTREAM_SCOPE="api://<downstream-api>/.default"
fi

echo -e "\n${GREEN}✓ Configuration values extracted:${NC}"
echo "  Tenant ID:        $TENANT_ID"
echo "  Client ID:        $CLIENT_ID"
echo "  Audience:         $AUDIENCE"
echo "  Downstream Scope: $DOWNSTREAM_SCOPE"
echo "  Client Secret:    ${CLIENT_SECRET:0:10}..." # Show only first 10 chars

# Export as environment variables
if [ "$USE_ENV_VARS" = true ]; then
  echo -e "\n${GREEN}📝 Exporting environment variables...${NC}"
  
  cat > "$PROJECT_ROOT/.env.local" <<EOF
# Auto-generated by setup-local-config.sh on $(date)
# Source this file: source .env.local

export AzureAd__TenantId="$TENANT_ID"
export AzureAd__ClientId="$CLIENT_ID"
export AzureAd__ClientSecret="$CLIENT_SECRET"
export AzureAd__Audience="$AUDIENCE"
export SuccessFactors__DownstreamScope="$DOWNSTREAM_SCOPE"
export SuccessFactors__SuccessFactorsBaseUrl="https://sandbox.api.sap.com/successfactors/odata/v2"
EOF

  echo -e "${GREEN}✓ Environment variables exported to: .env.local${NC}"
  echo -e "\nTo use these settings, run:"
  echo -e "  ${YELLOW}source .env.local${NC}"
  echo -e "  ${YELLOW}cd src/MCPWrapper/MCPWrapper.Api && dotnet run${NC}"
  
else
  # Update appsettings.Development.json
  echo -e "\n${GREEN}📝 Updating $APPSETTINGS_FILE...${NC}"
  
  # Create backup
  if [ -f "$APPSETTINGS_FILE" ]; then
    cp "$APPSETTINGS_FILE" "$APPSETTINGS_FILE.backup"
    echo "  Backup created: $APPSETTINGS_FILE.backup"
  fi
  
  # Create or update appsettings.Development.json using jq
  cat > "$APPSETTINGS_FILE" <<EOF
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "AzureAd": {
    "TenantId": "$TENANT_ID",
    "ClientId": "$CLIENT_ID",
    "ClientSecret": "$CLIENT_SECRET",
    "Audience": "$AUDIENCE"
  },
  "SuccessFactors": {
    "SuccessFactorsBaseUrl": "https://sandbox.api.sap.com/successfactors/odata/v2",
    "DownstreamScope": "$DOWNSTREAM_SCOPE"
  },
  "Mcp": {
    "ServerName": "SuccessFactors TimeOff MCP",
    "Version": "1.0.0"
  }
}
EOF

  echo -e "${GREEN}✓ Configuration file updated successfully!${NC}"
  echo -e "\nTo run the app locally:"
  echo -e "  ${YELLOW}cd src/MCPWrapper/MCPWrapper.Api && dotnet run${NC}"
fi

echo -e "\n${GREEN}=== Setup Complete ===${NC}"
